//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blood> Bloods { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassWiseSubjectInfo> ClassWiseSubjectInfoes { get; set; }
        public virtual DbSet<DesignationInfo> DesignationInfoes { get; set; }
        public virtual DbSet<DistrictInfo> DistrictInfoes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FMInformaton> FMInformatons { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<ProfessionType> ProfessionTypes { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<SectionInfo> SectionInfoes { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<StudentAcademicInfo> StudentAcademicInfoes { get; set; }
        public virtual DbSet<StudentInformation> StudentInformations { get; set; }
        public virtual DbSet<StudentType> StudentTypes { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<TutionFeeSetUp> TutionFeeSetUps { get; set; }
        public virtual DbSet<UnionInfo> UnionInfoes { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    
        public virtual int spDecreeOrder(string suitNo)
        {
            var suitNoParameter = suitNo != null ?
                new ObjectParameter("SuitNo", suitNo) :
                new ObjectParameter("SuitNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDecreeOrder", suitNoParameter);
        }
    }
}
