//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public long EmpID { get; set; }
        public string EmpName { get; set; }
        public long DesignationID { get; set; }
        public string EmpCode { get; set; }
        public long CompanyID { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public long CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long ModifyBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
