//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMInformaton
    {
        public int FMID { get; set; }
        public int StudentID { get; set; }
        public string FatherName { get; set; }
        public string FNID { get; set; }
        public string FProfession { get; set; }
        public int FProfessionType { get; set; }
        public decimal FYearlyIncome { get; set; }
        public string FMobile { get; set; }
        public string MotherName { get; set; }
        public string MNID { get; set; }
        public string MProfession { get; set; }
        public int MProfessionType { get; set; }
        public decimal MYearlyIncome { get; set; }
        public string MMobile { get; set; }
        public int CompanyID { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifyBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Status { get; set; }
    }
}
