//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PerID { get; set; }
        public int UserID { get; set; }
        public string MenuCode { get; set; }
        public bool UserPer { get; set; }
        public System.DateTime PerDate { get; set; }
        public bool chkRootMenu { get; set; }

    }
}
