//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAcademicInfo
    {
        public int SAcademicID { get; set; }
        public int StudentID { get; set; }
        public int ShiftID { get; set; }
        public int ClassID { get; set; }
        public int SectionID { get; set; }
        public int GroupID { get; set; }
        public string RollNo { get; set; }
        public int CompanyID { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifyBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Status { get; set; }
    }
}
