//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInformation
    {
        public int StudentID { get; set; }
        public string StudentCode { get; set; }
        public string StudentName { get; set; }
        public System.DateTime DOB { get; set; }
        public string BRN { get; set; }
        public int ReligionId { get; set; }
        public int GenderID { get; set; }
        public int BloodID { get; set; }
        public string Picture { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string StudentMobile { get; set; }
        public string GuardianMobile { get; set; }
        public int CompanyID { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifyBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public bool Status { get; set; }
    }
}
