//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionInfo
    {
        public string UnionID { get; set; }
        public string UpojillaID { get; set; }
        public string UnionName { get; set; }
        public long CompanyID { get; set; }
        public bool Active { get; set; }
        public string Remarks { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long ModifyBy { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
